name: avios
description: "A new Flutter project."
publish_to: "none"
version: 0.1.0

environment:
  sdk: ">=3.3.0 <4.0.0"

dependencies:
  firebase_auth: ^4.17.5
  firebase_core: ^2.25.4
  carousel_slider: ^4.2.1
  cloud_firestore: ^4.9.2
  dots_indicator: ^3.0.0
  firebase_storage: ^11.2.8
  google_mobile_ads: ^4.0.0
  google_sign_in: ^6.1.5
  http: ^1.1.0
  intl: ^0.19.0
  shared_preferences: ^2.2.2
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/images/
